version: '3.9'
services:
  notifiche:
    build: notifiche/.
    container_name: notifiche
    restart: 'no'
    environment:
      - service_name=notifiche
    depends_on:
      service_provider:
        condition: service_started
  stampa_sensibile:
    build: stampa_sensibile/.
    container_name: stampa_sensibile
    restart: 'no'
    environment:
      - service_name=stampa_sensibile
    depends_on:
      service_provider:
        condition: service_started
  timbrature:
    build: timbrature/.
    container_name: timbrature
    restart: 'no'
    environment:
      - service_name=timbrature
    depends_on:
      service_provider:
        condition: service_started
  service_provider:
    build: service_provider/.
    container_name: service_provider
    restart: 'no'
    ports:
      - "5000:5000"
    environment:
      - porta=5000
